---
- name: Create ONTAP Select cluster (ESXi)
  hosts: "localhost"
  gather_facts: false

  # -------------------
  # Read variable files
  # -------------------
  vars_files:
  - vars/vars_cluster.yml
  - vars/vars_cluster_pwd.yml
  roles:
    - na_ots_cluster
