# https://github.com/NetApp/ansible/tree/master/na_ontap_vserver_create

---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars_files:
    - vars/vars_cluster.yml
    - vars/vars_cluster_pwd.yml
  vars:
    svm_src: "svm-andrea-dr"
    svm_clone: "svm-andrea-clone"
    login: &login
      hostname: "{{ cluster_ip }}"
      username: "admin"
      password: "{{ ontap_pwd }}"
      https: yes
      validate_certs: no
  tasks:
  - name: Get CIFS Shares list
    na_ontap_info:
      state: info
      <<: *login
      gather_subset:
        - cifs_share_info
    register: ontap_info
  - debug:
      msg: "{{ ontap_info.ontap_info }}"

  - name: Loop over the CIFS Shares dictionary
    na_ontap_cifs:
      state: present
      share_name: "{{ item.value.share_name }}"
      path: "{{ item.value.path }}"
      vserver: "{{ svm_clone }}"
      share_properties: "{{ item.value.share_properties.cifs_share_properties }}"
      symlink_properties: read_only,enable
      <<: *login
    # na_ontap_cifs_acl:
    #   state: present
    #   share_name: "{{ item.value.share_name }}"
    #   user_or_group: Everyone
    #   permission: change
    with_dict: "{{ ontap_info.ontap_info.cifs_share_info }}"
    when: item.value.vserver == svm_src and item.value.share_name != "c$" and item.value.share_name != "admin$" and item.value.share_name != "ipc$"
