---
- name: Create ONTAP Select Deploy VM from OVA (ESXi)
  hosts: "{{ target_vcenter_or_esxi_host }}" # Entry in Ansible 'hosts' file
  gather_facts: false
  connection: 'local'
  vars_files:
  - vars/vars_deploy-install.yml # All Variables
  - vars/vars_deploy-install_pwd.yml # host_password & deploy_password
  roles:
    - na_ots_deploy
