---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars_files:
    - vars/vars_demo.yml
    - vars/vars_demo_login.yml
  vars:
    login: &login
      hostname: "{{ Cluster_B_IP }}"
      username: "{{ Cluster_B_username }}"
      password: "{{ Cluster_B_password }}"
      https: yes
      validate_certs: no
  tasks:
  - name: Create a new SVM
    na_ontap_svm:
      state: present
      name: "{{ svm_DR_clone }}"
      root_volume: "{{ svm_DR_clone_root }}"
      <<: *login

  - name: Setup DNS for the SVM
    na_ontap_dns:
      state: present
      vserver:  "{{ svm_DR_clone }}"
      domains: "{{ dns_domains }}"
      nameservers: "{{ dns_ips }}"
      skip_validation: true
      <<: *login

  - name: Create a new data LIF for the SVM
    na_ontap_interface:
      state: present
      vserver: "{{ svm_DR_clone }}"
      interface_name: "{{ svm_DR_clone_int_name }}"
      home_port: "{{ svm_DR_clone_int_home_port }}"
      home_node: "{{ svm_DR_clone_int_home_node }}"
      role: "{{ svm_DR_clone_int_role }}"
      protocols: "{{ svm_DR_clone_int_protocol }}"
      admin_status: up
      is_auto_revert: true
      address: "{{ svm_DR_clone_int_address }}"
      netmask: "{{ svm_DR_clone_int_netmask }}"
      #dns_domain_name: "{{ dns_domains[0] }}"
      <<: *login

  - name: "Join {{ svm_DR_clone }} to Active Directory as {{ svm_DR_clone }}"
    na_ontap_cifs_server:
      state: present
      service_state: started
      vserver: "{{ svm_DR_clone }}"
      name: "{{ svm_DR_clone }}"
      domain: "{{ AD }}"
      admin_user_name: "{{ AD_username }}"
      admin_password: "{{ AD_password }}"
      force: "yes"
      <<: *login
