---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars_files:
    - vars/vars_demo.yml
    - vars/vars_demo_login.yml
  vars:
    login: &login
      hostname: "{{ Cluster_B_IP }}"
      username: "{{ Cluster_B_username }}"
      password: "{{ Cluster_B_password }}"
      https: yes
      validate_certs: no
  tasks:
  - name: Get Ontap Info
    na_ontap_info:
      state: info
      <<: *login
      gather_subset:
        - volume_info
        - cifs_server_info
    register: ontap_info
#  - debug:
#     msg: "{{ ontap_info.ontap_info }}"

  - name: "Delete ALL CIFS shares in and UNJOIN from Active Directory"
    na_ontap_cifs_server:
      state: absent
      vserver: "{{ svm_DR_clone }}"
      name: "{{ svm_DR_clone }}"
      domain: "{{ item.value.domain }}"
      admin_user_name: "" #Force unjoin withouth a login
      admin_password: ""
      force: "yes"
      <<: *login
    with_dict: "{{ ontap_info.ontap_info.cifs_server_info }}"

  - name: Delete ALL Volumes
    na_ontap_volume:
      state: absent
      name: "{{ item.value.volume_id_attributes.name }}"
      #aggregate_name: ansible_aggr
      vserver: "{{ svm_DR_clone }}"
      <<: *login
    with_dict: "{{ ontap_info.ontap_info.volume_info }}"
    when: item.value.volume_id_attributes.owning_vserver_name == svm_DR_clone and item.value.volume_state_attributes.is_vserver_root == "false"

  - name: Delete SVM
    na_ontap_svm:
      state: absent
      name: "{{ svm_DR_clone }}"
      <<: *login
